"$schema" = "https://starship.rs/config-schema.json"

format = """
[\n]()\
$username\
$hostname\
$git_branch\
$git_status\
$nodejs$python$java\
$docker_context$conda$pixi\
$time\
[\n]()\
$directory\
[\n]()\
$character
"""

[os]
disabled = false
format = "[\\($symbol\\) ]($style)"
style = "fg:white bg:black"

[hostname]
ssh_only = false
ssh_symbol = "SSH "
format = "[$ssh_symbol@$hostname ]($style)"
style = "fg:white bg:black"

[username]
show_always = true
style_user = "fg:bright-white bg:black"
style_root = "fg:bright-red bg:black"
format = "[$user]($style)"

[directory]
style = "fg:cyan"
format = "[ $path ]($style)"
truncation_length = 0
before_repo_root_style = "fg:cyan"
repo_root_style = "fg:white"
use_logical_path = true
truncate_to_repo = false


[git_branch]
symbol = "git "
style = "fg:cyan "
format = "[ $symbol$branch ]($style)"

[git_status]
style = "fg:cyan"
format = "[ $all_status$ahead_behind ]($style)"

[c]
symbol = "C "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[cpp]
symbol = "C++ "
style = "/g:white bg:blue"
format = "[ $symbol$version ]($style)"

[rust]
symbol = "rs "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[golang]
symbol = "go "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[nodejs]
symbol = "node "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[python]
symbol = "py "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[java]
symbol = "java "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[kotlin]
symbol = "kt "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[haskell]
symbol = "hs "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[lua]
symbol = "lua "
style = "fg:black bg:blue"
format = "[ $symbol$version ]($style)"

[docker_context]
symbol = "docker "
style = "fg:white bg:bright-black"
format = "[ $symbol$context ]($style)"

[conda]
symbol = "conda "
style = "fg:white bg:bright-black"
format = "[ $symbol$environment ]($style)"

[pixi]
symbol = "pixi "
style = "fg:white bg:bright-black"
format = "[ $symbol$environment ]($style)"

[time]
disabled = false
time_format = "%R"
style = "fg:blue bg:bg"
format = "[ $time ]($style)"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_visual_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold magenta)"

